name: 编译
run-name: 编译
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: 设置 Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 设置 Nuitka 并编译
      uses: Nuitka/Nuitka-Action@v1.1
      with:
        nuitka-version: main
        windows-icon-from-ico: icon.ico
        script-name: main.py
        mode: standalone
        windows-console-mode: disable
        enable-plugins: pyqt5
        output-dir: dist
        company-name: DaYe
        product-name: WindowsCleaner
        file-version: 5.0.0
        product-version: 5.0
        file-description: WindowsCleaner
        copyright: DaYe
        trademarks: DaYe
    - name: 移动文件
      run:
        move WCMain/settings.json dist/main.dist/WCMain/settings.json
    - name: 上传文件
      uses: actions/upload-artifact@v4
      with:
        name: WindowsCleaner
        path: dist/main.dist
