name: 编译
run-name: 编译
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: 设置 Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: 安装依赖 & 编译
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -U pyinstaller    
        pyinstaller main.spec
    - name: 移动文件
      run:
        move WCMain dist/main/_internal/WCMain
    - name: 上传文件
      uses: actions/upload-artifact@v4
      with:
        name: WindowsCleaner
        path: dist
